export default Object.freeze({
    GET_SPECIALISTS_CALL : 'GET_SPECIALISTS_CALL',
    GET_EVENTS_CALL : 'GET_EVENTS_CALL',
    FILTER_SPECIALISTS : 'FILTER_SPECIALISTS',
    SHOW_SPECIALIST: 'SHOW_SPECIALIST',
    SET_FILTER_BAR_STATUS: 'SET_FILTER_BAR_STATUS',
    SET_FILTERS_LIST : 'SET_FILTERS_LIST'
});
